sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "dps75KV537BLhpWQmg5XzJTjD7jJVGzQbmKXqsLVGMR3L4yNwx7gVulubYxYJIW4O+81dYEaHvfNFqF/yjY4bgriibMQ5ORNvjXFNbLzbyG77MziLWzsnOV5q5GZgeJz4aPsPQaY8gGTtW1SqVKrhll3e01tlzXAgtPvkeHsHOJDZAquud9MxVUtYKqsu8NFWdC7iCqibvtUU/qwecUqXGULDTM9p7byYYT/AEOI+ty5ZOOKKREljwM3sDltgUCWReoE3qJx38VOhDQl9dfmhyplmX83eu0PqsHvJJdykCqXq7pmwNfYuxz6Gqw3zADLVwN1RkqxTjuyiYP3OvlbqSpzahrX3IADhUKpTwQeQDmorSR3gx5Vhgk47+E5PNOYHmMWr3UklCF+5XTKA4lSFzCaZKN8kv7MW0i0t0PPD/QRB8GI/LVyn6nDp6uvO8sjpdt6RnfrYgYTeox/fb8gmvksfRYEcgulcpMlNb6RkyNNFCs7MG/SXG9J0xTk+ooP39fQxbf1tGirJpJp/bwTdJ3zTGtyKNQJHsdlqPwZCn4dOGMCQ0jS805xUutFvWuBeFlnKW9pOp7RvwjOyhrNlKI53M5v0iB6rpmpOhnYVKwvbgrIsrHpa6daPzJxDX8z1QpBoZlln/kKp0sZKSCWC2UMt2ZuzhNBprE12jczhjw="
  - secure: "SebcGPtmG06kxkYDNR+Txi5zict2YZ4+NhYWtQXzQwf4faL7NywMxnizI84dr9v6UAYqdeCVCATMZtYyyFYfsxJEWW83dY7zQR2m/WaJ+OowGVUwugAVqWcx4fExEDUbhtVAH7yMcqosPG+VOt62G0oG7soQUVxFj0sGQ9B6e5fJfJJu6qHQpHY4syqY9l/0dCfk1/lvbeS724ALq3egUtYiBFal2rBcCMSB7T/6mxXq7vRc3e9uxOrbXqv8SGULZMFBB5Ibpv3G6dLIrJnFXbblDLxPMEgg6I9IxOIXA3H1T8Sy5zmr9pJKtjW7ApsJRsg0nkQ52Ipe5MAHynSRmEti9dvglYPZn3BOFy++t6uKfnmHPKYRnUzABiTdaWTWrhfJWLuZlqXjaoKYwCUD85Osne+VQvJhegphwIeq21wop0BjCyptU0URVz81teda95a4613t1hnRtkE51b3w2AlVkeZ0VYS28ZckPD7jolsHSHBqplioNt80wIyyP/zmvPYoinsPnKWqfYBHl6VX7ssVGw4dMJ5E0/UvGxDQk/UZYuwvi4j74tXgX5eUWb+Q+ZA0K3W1yowf3+6Y7DSaFTbmHml6tMw6S4DXom1dc/rX4rlBTUnCtIJ75xKuxgXSuy8d7wpUw+CRy/exO8Num3xEfzIg6Qt8ZGynEjKT98Y="  
  - secure: "vYGb5LbLeHvFZNjKOBxZymJJ9mlVi5UTQNA3BDKVXp7H6R9wBUv+LyR+g99UlY1kjSNMv1saFwZT0wzTXEG5eTf+tjww/m0AwJs35Feo/kQiYA4KK7i+tOyxQ8g5pwnjfsFLgVykiQxoavFf5QyHgNybo6U3hReRDx6JXahH3JxbC9UFmiZcxwu+SMmfQ291mHCYAq4j07wkHe8DxHNAhb3V+J2TPZf+U9hYH0VgyfVuxl+4bCIxdXylQy23pjkMmcLJSCQpB//+y+L83KCqGPSNDoyeO4MOJjsG7XuDmNWVyXpxnc0XOfFHy1DhSn826i3BZBn21mzWJTLu0IzIJ2eYEoylcKcvjXvuuwW/DLFb9D3/8Lr1TSWJ9Cb9csWtT+IFFiYr65S8T1UVWJVanfycfaPUuJhFOzlR3TN0Pbr+HskNIicWFK5bTnKqCBRiryrXgPG6ZGDUHYHjwGMsxw2FcUhDBNqX5AhY3Fwejk6e0U53nATbwZqPi70fVqPTeImBYV75YHToyDwwwceCzwd89XylC5aCnyF6Ah6GytT08SuG+eVCE5UnXldYNSn2jL62B9Q/dTCD2Hgid9uOr73OQt8cdFrMfxWgms11xN+qzJV1bBlUryPxEV2m862nQHoFYdkHe/XMS11GVXSgElgCFOEETmp8P6rXxs8uHRM="
  - secure: "N07ZpbbqsfI1d3SSVurlutO/4gxr3PCUygPmJyBGOlieV+v6W3QO+8sL9kPz8h+AmmsCWm/CJYEEc/ng4tYzWDNtdwQnC8zZFXrNhIF4SSZX5hHYdp6l3/Cx0HiQdkb1Xuy8oHZ4yv8d8YymVvU+R77zjDHtmL8OZTlMIPdiRCORVQk85SotHuDGcDWQcP/777WLjSkuyDr9WhdQHvzpbEDpabpPKjPYnC7V7IfALfhD/v36PRdUl5yjtOURWJDWMtpo0pdM0DdWN8EOY/uDvYHcsWxWWM5kcXkZA6sh0G86i5Gs0gOcnuYfbiL/i/vt5YUE3Nv42ZS9lxKqgPDyrv++lJZX9+/A+JGe+Ow3y0JjhQ8Wfd71wQQXE3KUbmPr5aDea5GpebDgGCRivAfyN1/yQQMLIGRV4OsdnqGj2IINx9KdFCf9xPtRf/ZfYHkp7g0Q4ofBkQ16WKuzFm8INgQ0rUE9O7waOxKCDIhlNhSwQcEP3piHGTmJ+Ko5dr9+Q9HpPU6OR8oXv5+ZXtmJ/7kgyhwsJFFlQeMNc9hJfUjadtBHsVItBZ1ztw+o//rtAZtK1qfpLvkWbbjX5yYEQ6hld0U5wLHT88aPk5lSj9vm2hxtGy9vAiji2z6DTvQ/qTTb8bP3xENdajABZCz5odu5bGPkvI2r4m6M+9k+r1Y="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
