sudo: false

language: c

addons:
  apt:
    packages:
    - lua5.1
    - luarocks

env:
  global:
  - secure: "w4UlAg2Fj9r7PvVlmLY4nV0L14w8ud/AC0AaSua6gfDjPby7Wujpoflc8Fq4QCMgrnmdU1FxMs8PQ1yuIxDNHQbxObhz+mOQ+EOCVwfhz7GJcjDxOIqDNUfAvX0jsWeQrgA+n+1AZPmApMgE14ZJzW75pQgEoK97HAlfid9m0ol3Jc/5Xt8cwCiVl4cKy1LYorJw3Wsl957wqMdSmun7VEX7vgezsnz5EsIkGR8Nf+RYe6+fVdGp3q/EWmzGHWOg7U6/MWl1ipQ3FHRctSosa8rEoiqbhcP4ulWXPjO/sjWniZSy2QULabHHtF5GbrtEGqYj1L1GIC/rXuXAvGvDDTwzZKIsPrPTsACx8P4BQSrYrwQMLBQyjobxzaxh1CO8bzo7mSNL7CMYqtLJxILbQc+Gk0C57fjG8BYsz58zB2NdJDjPzgchI5qxnRVx94rQg5oRo+SM1a9BiyDBc2bKlNFa2TZM4/+wpRVzYfPShmSP8/Z7828Lv16HZBcQEe/Y0WqphxKj5nEP6ecz5oU5ZrSsZdAg0tGy5WgBL9iq6wGNNpmFPI3oYkmBKHYaFeaIkZwicmJr1K6kefs4dvVwy9ZrvgBTK16mY293X9/QbFlF3I5TNf8YwfzlvbYsg+Mp2ylqX2Mr9REFKbz1vDLz1/yQPNLQHuO4v4z8+eUMXlI="
  - secure: "SebcGPtmG06kxkYDNR+Txi5zict2YZ4+NhYWtQXzQwf4faL7NywMxnizI84dr9v6UAYqdeCVCATMZtYyyFYfsxJEWW83dY7zQR2m/WaJ+OowGVUwugAVqWcx4fExEDUbhtVAH7yMcqosPG+VOt62G0oG7soQUVxFj0sGQ9B6e5fJfJJu6qHQpHY4syqY9l/0dCfk1/lvbeS724ALq3egUtYiBFal2rBcCMSB7T/6mxXq7vRc3e9uxOrbXqv8SGULZMFBB5Ibpv3G6dLIrJnFXbblDLxPMEgg6I9IxOIXA3H1T8Sy5zmr9pJKtjW7ApsJRsg0nkQ52Ipe5MAHynSRmEti9dvglYPZn3BOFy++t6uKfnmHPKYRnUzABiTdaWTWrhfJWLuZlqXjaoKYwCUD85Osne+VQvJhegphwIeq21wop0BjCyptU0URVz81teda95a4613t1hnRtkE51b3w2AlVkeZ0VYS28ZckPD7jolsHSHBqplioNt80wIyyP/zmvPYoinsPnKWqfYBHl6VX7ssVGw4dMJ5E0/UvGxDQk/UZYuwvi4j74tXgX5eUWb+Q+ZA0K3W1yowf3+6Y7DSaFTbmHml6tMw6S4DXom1dc/rX4rlBTUnCtIJ75xKuxgXSuy8d7wpUw+CRy/exO8Num3xEfzIg6Qt8ZGynEjKT98Y="
  - secure: "zc9wpe5ii6ykMGFl9sGiybi/RHEW3OrtDO6ciXPJ5Wd0WzWUithv5uDayeeZ9DkCL+cA6YMtD9p17Ml5c4+Ve42uL0iaMqvCNvvgQDSOf34MzSzKTsEgZCnkm+tuk2GWBynJZ2r7lBBVIKmfITQETMqYi8qiWOTaLEsoh7TeeD1moXM5kHLCFf+0BKOzdZo8mGH8lrR/kLvuYvCATTmvrFQ9QShBXGGu+BvUs21VdHs/Ktn34xnLO+oRUQgjaMXk+6fd7xwa53pvuC5noJk4cUWBJqpG/qntCXIBq3HWpurfwY1j7TOCQ860721AggrdGEF2WoK1Mh99HrCg7w2bB79tErWDOC/nJjvYd8mtZ9jrsG1hl8zVjZrdt+uuaoY2v1eCM09ruVE7I8ce1MVIXonk8d4QglK9+P+dYoSEPaJxb5gduIzMIOZRn1Y0YaeY5Hne2/c/pAbDMPC3txGyMzxMdlsXDDJ4HdjsxKI9YxNtR6kXN6J0Xty/8xxcvksghVePMBIuPK22XQAJgT0Tko7tAt/m+WA9Lze8DHZW0a5xu6IzMOBPQ6a2M9fI3YALUptBmRiTro2CPUozgpjVcqJ4dF2yJT7l996T6g7vhww11NwAW2hEj9k044b/CthZ+1FrP+xUgntiiSYtcA2U+a+TWJvAH86GUFOTHh1jAO0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
