sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "vakAo9+mqSyo7/tRg10btiR9dh6E5EsUz5SN/DkWWM/McBsj/wi3gI9dUe6V7XNEcn4i25GfmaQh1yB45qoW3HRhRfjl9XDFaC6+FRQ2kjW/CSBXzTb3SiloAMjelkponQrbqp+yUEmzuc+gMBjmp8F7cqGCV3s4IaEb71U94KxTAKCdDKzN314T/ER2sUo1YWUagSauPIbm9V84e0Up3fb9jmi2VPAI4n78g8H0aYb1EwVV9mukoz8Vs6LyoFT43rsw84c2ynid/XE5gKKq4FGEzpP4lVbn6p7OfXESjatyYm/BZPh/12pK+4hcd03BsF6oYT7cUSy6ymWrD0JXwT6BoTBNksvRZXIZp/3v0UEJoJcTJc3qVsu+hTolco3yO5ob/0zAUJqeVYlJw2P7+QcQ9qJtRycOks9MNhZhvksm1UGw6NL8z2ZGmZarcOz5WcgWm8PDSdfLugKkE3IB+2jQvJ9W3NztbZ4Hz97dJ0IQRZdJODqJ+E5TixNvYiScsy0RyU3fNdUeW8Ocn4/C5Nr57OO0pXwjWP9hQYcqNxtNXFD8VRhRSP7Dcck4Dy+5Ga5MpziRMkX2aASxq9lU8+XSQBEYsXUKXmkvwhpssAu/UN8vn6VwOZJHKHxSOw18T3CxVBK6Pr5VTrUbKQRQRXzIhsuXijPdtAjM8bnC7CY="
  - secure: "SebcGPtmG06kxkYDNR+Txi5zict2YZ4+NhYWtQXzQwf4faL7NywMxnizI84dr9v6UAYqdeCVCATMZtYyyFYfsxJEWW83dY7zQR2m/WaJ+OowGVUwugAVqWcx4fExEDUbhtVAH7yMcqosPG+VOt62G0oG7soQUVxFj0sGQ9B6e5fJfJJu6qHQpHY4syqY9l/0dCfk1/lvbeS724ALq3egUtYiBFal2rBcCMSB7T/6mxXq7vRc3e9uxOrbXqv8SGULZMFBB5Ibpv3G6dLIrJnFXbblDLxPMEgg6I9IxOIXA3H1T8Sy5zmr9pJKtjW7ApsJRsg0nkQ52Ipe5MAHynSRmEti9dvglYPZn3BOFy++t6uKfnmHPKYRnUzABiTdaWTWrhfJWLuZlqXjaoKYwCUD85Osne+VQvJhegphwIeq21wop0BjCyptU0URVz81teda95a4613t1hnRtkE51b3w2AlVkeZ0VYS28ZckPD7jolsHSHBqplioNt80wIyyP/zmvPYoinsPnKWqfYBHl6VX7ssVGw4dMJ5E0/UvGxDQk/UZYuwvi4j74tXgX5eUWb+Q+ZA0K3W1yowf3+6Y7DSaFTbmHml6tMw6S4DXom1dc/rX4rlBTUnCtIJ75xKuxgXSuy8d7wpUw+CRy/exO8Num3xEfzIg6Qt8ZGynEjKT98Y="
  - secure: "qG4NzXayuC+roUxepZU/mcPUvvccVJH6gsoa4F2cDbFQbKn6ZIgdH1yGs0rPfgDIt1tuSZYqhqjwYT5U3yGTv5uHYymYpZ59dvINAlb/6fIAzOVI2wrv64yTitVZCXZR452LD9dyLkjzZFuROWLE2+AIXOOPKuLoN386SWpUE9spweChq5yR4Zc3zZPF9u7TBvcxE3Ji/SPf4Z4PkGc7CnuCxQFpKh9+ZLvdzWNw1gi/Kt5tzeZCukcxOy6usL0aB4Df+/5LjZysp8Qtuziq3fJRnnxCNZPb77sbHAIPgjmxH9VKEk83eeclzAvTlkr5vUaHxfvp1zzEiqnpE+QTRH/7Hr3ksrd02pvHDLKHQukndnFtywJ0ygt1YffW3Xns0yQ5vTh2vAlk233sKdl/Ik3kxmVMjew+63n5JNoXxO5/u6rZI6aTxwEuZ581/pGpJN8uBzsBx+RLCF67KEZc/2m9sPrVOs7JSHN95Ui8qQI5DnYRcRAUVE0iIDiM+lZQldvI7wlLHPI34LMOM/3F+day1PMhw7Vx0cJfWA25vVVMKWhgJYnwEulsLDd9NHNihTkoRES7Xwv7rV2MU360lUhVg6bH1H2tFS/u7/nouZ+Mwjg9A7+qAlv6dSFQTNJ/+w8En3j9LDy+dVhLIPWP41rgMvGeqMcHwBZm33maf5Q="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
